insert into long_products
(type, name, price, img, description)
values
('complete', 'NATURAL MYSTIC', 189, 'https://cdn.shopify.com/s/files/1/2291/8079/products/NATURAL-MYSTIC-1800x1800_2048x.png?v=1530845016', 'Flow smoothly through the streets on the Natural Mystic, the longest board in this season’s Marley series. From traditional carves to long-distance pushing, this vehicle is sure to put a smile on your face (but maybe not as big as Bob’s), as you groove to your personal soundtrack. There’s nothing mysterious about it - if you’re looking for a commuter or a carver, this board is a solid choice.'),
('complete', 'STACKED STRAND', 139, 'https://cdn.shopify.com/s/files/1/2291/8079/products/STACKED-STRAND-1800x1800_da2620f8-eaec-4c81-b769-6abcc114f11e_2048x.png?v=1530844235', 'The 9-Ball Crew can’t stare at the bottom graphic of the new Strand too long, because we can’t stop mind-surfing the stacked lines from artist Erik Abel! Having the shortest wheelbase in this season’s bamboo collection provides the Strand with a sharp turning radius and a functional kicktail will allow you to ollie over anything that gets in your way down to the corner store.'),
('complete', 'VISTA LEDGER', 159, 'https://cdn.shopify.com/s/files/1/2291/8079/products/VISTA-LEDGER-1800x1800_2048x.png?v=1526509334', 'The sleek, classic pintail commonly known to the 9-Ball Crew as ''The Ledger'' provides a clean, smooth ride from the mountains to the sea and everywhere in-between!.  A direct descendent of our OG Pin, this easy-to-ride board provides entertainment for the whole family and the new duotone dip-dyed veneers make the updated graphic ''POP'' louder than ever.  Now go lay down some classic lines!'),
('complete', 'ECHO FRACTAL', 199, 'https://cdn.shopify.com/s/files/1/2291/8079/products/ECHO-FRACTAL-1800x1800_2048x.png?v=1526509991', 'The Fractal is the best-selling shape in our Sidewinder Series, and this season we''ve partnered with photographer Ben Thouard to provide you with an inside-the-barrel perspective from deep within a South Pacific dreamer. Let this view be your inspiration to get out there and surf the streets! Our 69MM Top Shelf wheels and ABEC 5 bearings will provide you the speed needed for a clean exit.'),
('complete', 'HEX DROPPER', 219, 'https://cdn.shopify.com/s/files/1/2291/8079/products/HEX-DROPPER-1800x1800-2_2048x.png?v=1530056920', 'Drop-through truck mounts and a 0.625" drop rocker create a low center of gravity, making this board both stable and easy to push (not to mention amazingly easy to slide!). The symmetrical shape and kicktails lend themselves to freeride and freestyle fun.  Our updated color scheme on the Dropper may make it look too good to ride, but don''t let that keep you from locking into some good slides on this well-known Sector 9 shredder'),
('complete', 'RIPPED JIMMY PRO', 199, 'https://cdn.shopify.com/s/files/1/2291/8079/products/RIPPED-JIMMY-PRO-1800x1800_edd988d6-21a4-479d-a6a9-8e41fca7201b_2048x.png?v=1530056628', 'Harness the eye of the tiger with the Ripped Jimmy Pro and be more than ready to attack any terrain.  This all-around downhill board features a mellow combination of micro-drop and rocker for a comfortable ride, while locking your feet in place.  Flush mounts keep your board lower to the ground for stability and to keep your truck angles true. The functional kick tail allows slow speed fun, as you’ll be snapping ollies no matter where you are!'),
('complete', 'RIPPED JACKO PRO', 199, 'https://cdn.shopify.com/s/files/1/2291/8079/products/RIPPED-JACKO-PRO-1800x1800_fa0108fd-2bb6-4c9f-ada5-26465f5b18b8_2048x.png?v=1530056778', 'Oi! Oi! Oi! Get straight to business with the updated Jacko Pro, which is now a few inches shorter from the past model.  The classic Sector 9 race outline and aggressive concave work together to ensure you’ll be locked in and ready to rally from the moment you step on.  Wheel flares in the front and rear act as natural foot-stops to keep your feet from unwanted movement, while the non-invasive W-concave towards the middle of the board adds rigidity. A short wheelbase race-rocket or a surfy feeling free-rider, rip your way through any situation on the Ripped Jacko Pro.'),
('complete', 'GEO LOOKOUT', 199, 'https://cdn.shopify.com/s/files/1/2291/8079/products/GEO-LOOKOUT-1800x1800_2048x.png?v=1530844755', 'There is no better carving and commuting vehicle than the Bamboo version of the Lookout, which is why it is our top-selling board. The complete version comes with 69mm wheels to keep your speed and easily roll over cracks and any stray rocks that get in your way. The drop-through truck mounts make the board lower, easier to push, and more stable. The Bamboo construction keeps the board light, gives it a nice dampening flex, and is a renewable resource.'),
('complete', 'BALANCE BINTANG', 179, 'https://cdn.shopify.com/s/files/1/2291/8079/products/BALANCE-BINTANG-1800x1800_2048x.png?v=1530841432', 'Our latest version of the Bintang continues to deliver proven versatility to the rider. As a commuter, easy pushing and long distance gliding are part of the package and if you’re looking for freeride fun, the board’s sharp rails provide extra grip and control, and our stone-ground Buttersauce wheels provide easier slides.'),
('complete', 'WEEKEND MERIDIAN GREEN', 189, 'https://cdn.shopify.com/s/files/1/2291/8079/products/WEEKEND-MERIDIAN-RASTA-1800x1800_2048x.png?v=1530842988', 'The Weekend Meridian will provide you with versatile riding, ANY day of the week – not just Saturday and Sunday! This time around, we’ve updated this best-selling board with a new graphic (in two colors) and fresh wheel colors. It doesn’t matter if you’re in the city, at the beach, or in the mountains, this board will allow you push, glide and slide with comfort and ease.'),


('deck', 'ISLAND MASON PRO DECK', 65, 'https://cdn.shopify.com/s/files/1/2291/8079/products/1b94d13de94127e8e3e4d806d1230165_2048x.png?v=1522286191', 'Is there anyone on the planet having as much fun as Mason Ho?  The guy exudes pure stoke, 24/7, and this board is his first Signature Sector 9 model.  If you''ve ever had.  With that in mind, we worked closely with him to develop a super fun board that is extremely versatile. Whether charging your local ditch, cruising the boardwalk, or having a session at your local skatepark, the Mason Pro should be a ''go-to'' for anyone looking for a good time! '),
('deck', 'OUTTHERE DECK', 65, 'https://cdn.shopify.com/s/files/1/2291/8079/products/4046dba3c2445baf555bd9b0ebf51544_2048x.png?v=1522286253', 'It’s OK, don’t be embarrassed, just admit it.  You quickly got in way over your head and paid the price, via an epic slam – WE ALL HAVE!  Now, it’s time to get some redemption on the Sector 9 x Kookslams #OUTTHERE!  This incredibly fun cruiser is easy-to-ride and will help you forget all about those embarrassing slams! #actlikeitdidnthappen #yesitwascaughtonfilm #wakeupandslam'),
('deck', 'RIPPED JACKO PRO DECK', 90, 'https://cdn.shopify.com/s/files/1/2291/8079/products/RIPPED-JACKO-PRO-DECK_2048x.png?v=1526317390', 'Oi! Oi! Oi! Get straight to business with the updated Jacko Pro, which is now a few inches shorter from the past model.  The classic Sector 9 race outline and aggressive concave work together to ensure you’ll be locked in and ready to rally from the moment you step on.  Wheel flares in the front and rear act as natural foot-stops to keep your feet from unwanted movement, while the non-invasive W-concave towards the middle of the board adds rigidity. A short wheelbase race-rocket or a surfy feeling free-rider, rip your way through any situation on the Ripped Jacko Pro.'),
('deck', 'TROPICS LEDGER DECK', 86, 'https://cdn.shopify.com/s/files/1/2291/8079/products/TROPICS-LEDGER-DECK_2048x.png?v=1522788891', 'If you think a ''ledger'' can be described as a book with lots of columns, on which an accountant keeps tracks of debits and credits, then you''re talking to the wrong people.  Our ''Ledger'' is a sleek, classic pintail made for carving and providing you with an enjoyable commute. If you''re stuck in the city, just flip it over and our updated graphic will transport you to a stress-free, palm tree-lined beach.'),
('deck', 'STACKED STRAND DECK', 69, 'https://cdn.shopify.com/s/files/1/2291/8079/products/STACKED-STRAND-DECK_2048x.png?v=1525717330', 'The 9-Ball Crew can’t stare at the bottom graphic of the new Strand too long, because we can’t stop mind-surfing the stacked lines from artist Erik Abel! Having the shortest wheelbase in this season’s bamboo collection provides the Strand with a sharp turning radius and a functional kicktail will allow you to ollie over anything that gets in your way down to the corner store.'),
('deck', 'ECLIPSE BONSAI DECK', 80, 'https://cdn.shopify.com/s/files/1/2291/8079/products/ECLIPSE-BONSAI-DECK_2048x.png?v=1525717583', 'At 42” in length, the Bonsai is the second longest board in the entire Sector 9 lineup, this season, after the 25 Year OG Pin. Drawing on our traditional heritage of pintails, this skateboard doesn’t care if you’re 6 years old or 60 – either way it’s going to show you a good time and keep you wanting to come back for more. Hopefully, it can transport you to the right-hand point artist Erik Abel has put on the bottom!'),
('deck', '25 YEAR BHNC DECK', 99, 'https://cdn.shopify.com/s/files/1/2291/8079/products/25-YEAR-BHNC-DECK_2048x.png?v=1529358769', 'The original release of the Bomb Hills Not Countries board created a memorable statement, heard around the world.  Over the years that followed, we consistently received requests to reissue this board, so it made complete sense to include it in the 25 Year Anniversary Limited Edition Series.  The deck construction on this classic shape features a unique, multi-color ply, making each board truly one of a kind! Enjoy this perfect high-speed carving vehicle that also allows you to take control of tough, steep terrain.'),
('deck', 'RAY COLLINS MERCHANT DECK', 85, 'https://cdn.shopify.com/s/files/1/2291/8079/products/RAY-COLLINS-MERCHANT-DECK_2048x.png?v=1530839476', 'Cruising and carving have never been easier, when you’re riding the Merchant, and we’ve made this ageless Sector 9 shape look better than ever with Ray’s POV from inside the barrel. The 25.75” wheelbase combined with 65MM Top Shelf wheels and Gullwing Charger trucks will provide you with the tools to draw unique lines on the pavement, and guarantee you endless fun from sunrise to sunset.'),
('deck', 'DREAM GRAVY SEMI PRO DECK', 69, 'https://cdn.shopify.com/s/files/1/2291/8079/products/DREAM-GRAVY-SEMI-PRO-DECK_2048x.png?v=1539808605', 'What’s your claim? Ben Gravy is claiming his new Semi-Pro model will provide you with the most fun you’ve ever had on a skateboard!  Purposely designed with versatility in mind, this board will allow you to body-bag your local skatepark, cruise down to your version of El Slammo for a surf check, hit every novelty skate spot in your neighborhood and will then quickly transport you to the nearest convenience store for a post-session coffee and vegan cookie. For the dream!'),
('deck', 'TACKLE FRACTAL DECK', 199, 'https://cdn.shopify.com/s/files/1/2291/8079/products/TACKLE-FRACTAL-DECK_2048x.png?v=1537907577', 'While Salty Timbers has created an angler’s dream on underside of the Tackle Fractal, we’re confident in saying this board will provide you with the type of turns that skaters dream of! The Sidewinder trucks feature a patented double kingpin style and are best suited for carving.  The knurled kingpins stay securely in place while riding and will allow you to carve harder, deeper and smoother than you’ve ever imagined!  Consistently on our best-seller list, this shape is dropped down for easy pushing, carving and pumping, and will surely provide the type of ride you’ve been craving.'),


('wheels', 'Arbor Bogart 61mm 78a White Wheels', 35, 'https://cdn8.bigcommerce.com/s-wug401/images/stencil/540x540/products/4669/29741/wheels920_000__18414__19999.1538007630.png?c=2&imbypass=on', 'The Arbor 61mm 78a Bogart White wheels are designed for freeriding, carving, and cruising. The firm durometer maintains speed over smooth surfaces. The rounded lips and stoneground surface produce natural slides.'),
('wheels', 'Arbor Easy Rider Outlook 69mm 78a Ghost Black Wheels', 39, 'https://cdn8.bigcommerce.com/s-wug401/images/stencil/540x540/products/6929/30504/wheels_34__64645__93892.1538007757.png?c=2&imbypass=on', 'The Arbor 69mm 78a Easy Rider Outlook wheels are designed for freeriding, carving, and cruising. The firm durometer maintains speed over smooth surfaces. The rounded lips and stoneground surface produce natural slides. '),
('wheels', 'Arbor Mosh 65mm 78a Green Wheels', 37, 'https://cdn8.bigcommerce.com/s-wug401/images/stencil/540x540/products/4673/29743/wheels_32__32046__16070.1538007630.png?c=2&imbypass=on', 'The Arbor Mosh 65mm 78a Green wheels are designed for freeriding and cruising. With a firm durometer to maintain speed, the rounded lips are ideal for sliding.'),
('wheels', 'Arbor Spud 64mm 82a Red Wheels', 43, 'https://www.thelongboardstore.com/wheels/arbor/arbor-spud-64mm-82a-red-wheels/', 'The Arbor Spud 64mm 82a wheels are designed for freeriding. With rounded lips and stoneground surface for sliding, the firm durometer maintains a quick roll speed.'),
('wheels', 'Arbor Vice 69mm 80a White Wheels', 45, 'https://cdn8.bigcommerce.com/s-wug401/images/stencil/540x540/products/4679/29747/wheels3_03__89108__36441.1538007631.png?c=2&imbypass=on', 'The Arbor Vice 69mm 80a White wheels are designed for freeriding. With rounded lips and stoneground surface for sliding, the firm durometer maintains a quick roll speed.'),
('wheels', 'Blood Orange Morgan 70mm 82a Lavender Wheels', 49, 'https://www.thelongboardstore.com/categories/wheels.html', 'The Blood Orange Morgan 70mm 82a Lavender wheels are designed for freeriding and cruising. The tallest of the Morgan Series, the stoneground surface and rounded lips produce natural slides. The firm durometer maintains a quick roll speed over smooth terrain. '),
('wheels', 'Cadillac Sugar Mamas 65mm 78a Blue Wheels', 43, 'https://cdn8.bigcommerce.com/s-wug401/images/stencil/540x540/products/5566/29943/wheels_35__43439__30028.1538007667.png?c=2&imbypass=on', 'The Cadillac Sugar Mamas 65mm 78a Blue wheels are designed for freeriding and cruising. With rounded lips for slides, the soft durometer absorbs shock over rough terrain. '),
('wheels', 'Hawgs Mini Monster 70mm 78a Blue Wheels', 50, 'https://cdn8.bigcommerce.com/s-wug401/images/stencil/540x540/products/5557/30988/wheels920_008__92712.1537467954.1280.1280__94688.1538011451.png?c=2&imbypass=on', 'The Hawgs Mini Monster 70mm 78a Blue wheels are designed for cruising, carving, freeride, and downhill. With a slightly chamfered lip for grip and slip, the softer durometer absorbs shock over rough terrain. '),
('wheels', 'Orangatang Onsens 58mm 100a Blue Wheels', 35, 'https://cdn8.bigcommerce.com/s-wug401/images/stencil/540x540/products/6578/30326/onsen-mediumres(1)__55993__82443.1538007731.jpg?c=2&imbypass=on', 'The Orangatang Onsens 58mm 100a Blue wheels are designed for street, park and pool riding. With a hard durometer to maintain a fast roll speed over smooth terrain, the rounded lips provide grip in combination with the sanded finish. The core is created with heat resistant, high strength, and glass-free urethane.  Sold in a set of 4 wheels'),
('wheels', 'RAD Release 72mm 78a White Wheels', 54, 'https://cdn8.bigcommerce.com/s-wug401/images/stencil/540x540/products/3687/29467/radreleasewhite__65582__18872.1538007583.png?c=2&imbypass=on', 'The RAD Release 72mm 78a White wheels are designed for freeriding. With a stoneground surface and rounded lips for sliding, the soft durometer reduces vibration over rough terrain.  Sold in a set of 4 wheels.');