insert into long_products
(type, name, price, img, description)
values
('complete', 'NATURAL MYSTIC', 189, 'https://cdn.shopify.com/s/files/1/2291/8079/products/NATURAL-MYSTIC-1800x1800_2048x.png?v=1530845016', 'Flow smoothly through the streets on the Natural Mystic, the longest board in this season’s Marley series. From traditional carves to long-distance pushing, this vehicle is sure to put a smile on your face (but maybe not as big as Bob’s), as you groove to your personal soundtrack. There’s nothing mysterious about it - if you’re looking for a commuter or a carver, this board is a solid choice.'),
('complete', 'STACKED STRAND', 139, 'https://cdn.shopify.com/s/files/1/2291/8079/products/STACKED-STRAND-1800x1800_da2620f8-eaec-4c81-b769-6abcc114f11e_2048x.png?v=1530844235', 'The 9-Ball Crew can’t stare at the bottom graphic of the new Strand too long, because we can’t stop mind-surfing the stacked lines from artist Erik Abel! Having the shortest wheelbase in this season’s bamboo collection provides the Strand with a sharp turning radius and a functional kicktail will allow you to ollie over anything that gets in your way down to the corner store.'),
('complete', 'VISTA LEDGER', 159, 'https://cdn.shopify.com/s/files/1/2291/8079/products/VISTA-LEDGER-1800x1800_2048x.png?v=1526509334', 'The sleek, classic pintail commonly known to the 9-Ball Crew as ''The Ledger'' provides a clean, smooth ride from the mountains to the sea and everywhere in-between!.  A direct descendent of our OG Pin, this easy-to-ride board provides entertainment for the whole family and the new duotone dip-dyed veneers make the updated graphic ''POP'' louder than ever.  Now go lay down some classic lines!'),
('complete', 'ECHO FRACTAL', 199, 'https://cdn.shopify.com/s/files/1/2291/8079/products/ECHO-FRACTAL-1800x1800_2048x.png?v=1526509991', 'The Fractal is the best-selling shape in our Sidewinder Series, and this season we''ve partnered with photographer Ben Thouard to provide you with an inside-the-barrel perspective from deep within a South Pacific dreamer. Let this view be your inspiration to get out there and surf the streets! Our 69MM Top Shelf wheels and ABEC 5 bearings will provide you the speed needed for a clean exit.'),
('complete', 'HEX DROPPER', 219, 'https://cdn.shopify.com/s/files/1/2291/8079/products/HEX-DROPPER-1800x1800-2_2048x.png?v=1530056920', 'Drop-through truck mounts and a 0.625" drop rocker create a low center of gravity, making this board both stable and easy to push (not to mention amazingly easy to slide!). The symmetrical shape and kicktails lend themselves to freeride and freestyle fun.  Our updated color scheme on the Dropper may make it look too good to ride, but don''t let that keep you from locking into some good slides on this well-known Sector 9 shredder'),
('complete', 'RIPPED JIMMY PRO', 199, 'https://cdn.shopify.com/s/files/1/2291/8079/products/RIPPED-JIMMY-PRO-1800x1800_edd988d6-21a4-479d-a6a9-8e41fca7201b_2048x.png?v=1530056628', 'Harness the eye of the tiger with the Ripped Jimmy Pro and be more than ready to attack any terrain.  This all-around downhill board features a mellow combination of micro-drop and rocker for a comfortable ride, while locking your feet in place.  Flush mounts keep your board lower to the ground for stability and to keep your truck angles true. The functional kick tail allows slow speed fun, as you’ll be snapping ollies no matter where you are!'),
('complete', 'RIPPED JACKO PRO', 199, 'https://cdn.shopify.com/s/files/1/2291/8079/products/RIPPED-JACKO-PRO-1800x1800_fa0108fd-2bb6-4c9f-ada5-26465f5b18b8_2048x.png?v=1530056778', 'Oi! Oi! Oi! Get straight to business with the updated Jacko Pro, which is now a few inches shorter from the past model.  The classic Sector 9 race outline and aggressive concave work together to ensure you’ll be locked in and ready to rally from the moment you step on.  Wheel flares in the front and rear act as natural foot-stops to keep your feet from unwanted movement, while the non-invasive W-concave towards the middle of the board adds rigidity. A short wheelbase race-rocket or a surfy feeling free-rider, rip your way through any situation on the Ripped Jacko Pro.'),
('complete', 'GEO LOOKOUT', 199, 'https://cdn.shopify.com/s/files/1/2291/8079/products/GEO-LOOKOUT-1800x1800_2048x.png?v=1530844755', 'There is no better carving and commuting vehicle than the Bamboo version of the Lookout, which is why it is our top-selling board. The complete version comes with 69mm wheels to keep your speed and easily roll over cracks and any stray rocks that get in your way. The drop-through truck mounts make the board lower, easier to push, and more stable. The Bamboo construction keeps the board light, gives it a nice dampening flex, and is a renewable resource.'),
('complete', 'BALANCE BINTANG', 179, 'https://cdn.shopify.com/s/files/1/2291/8079/products/BALANCE-BINTANG-1800x1800_2048x.png?v=1530841432', 'Our latest version of the Bintang continues to deliver proven versatility to the rider. As a commuter, easy pushing and long distance gliding are part of the package and if you’re looking for freeride fun, the board’s sharp rails provide extra grip and control, and our stone-ground Buttersauce wheels provide easier slides.'),
('complete', 'WEEKEND MERIDIAN GREEN', 189, 'https://cdn.shopify.com/s/files/1/2291/8079/products/WEEKEND-MERIDIAN-RASTA-1800x1800_2048x.png?v=1530842988', 'The Weekend Meridian will provide you with versatile riding, ANY day of the week – not just Saturday and Sunday! This time around, we’ve updated this best-selling board with a new graphic (in two colors) and fresh wheel colors. It doesn’t matter if you’re in the city, at the beach, or in the mountains, this board will allow you push, glide and slide with comfort and ease.'),


('deck', 'ISLAND MASON PRO DECK', 65, 'https://cdn.shopify.com/s/files/1/2291/8079/products/1b94d13de94127e8e3e4d806d1230165_2048x.png?v=1522286191', 'Is there anyone on the planet having as much fun as Mason Ho?  The guy exudes pure stoke, 24/7, and this board is his first Signature Sector 9 model.  If you''ve ever had.  With that in mind, we worked closely with him to develop a super fun board that is extremely versatile. Whether charging your local ditch, cruising the boardwalk, or having a session at your local skatepark, the Mason Pro should be a ''go-to'' for anyone looking for a good time! '),
('deck', 'OUTTHERE DECK', 65, 'https://cdn.shopify.com/s/files/1/2291/8079/products/4046dba3c2445baf555bd9b0ebf51544_2048x.png?v=1522286253', 'It’s OK, don’t be embarrassed, just admit it.  You quickly got in way over your head and paid the price, via an epic slam – WE ALL HAVE!  Now, it’s time to get some redemption on the Sector 9 x Kookslams #OUTTHERE!  This incredibly fun cruiser is easy-to-ride and will help you forget all about those embarrassing slams! #actlikeitdidnthappen #yesitwascaughtonfilm #wakeupandslam'),
('deck', 'RIPPED JACKO PRO DECK', 90, 'https://cdn.shopify.com/s/files/1/2291/8079/products/RIPPED-JACKO-PRO-DECK_2048x.png?v=1526317390', 'Oi! Oi! Oi! Get straight to business with the updated Jacko Pro, which is now a few inches shorter from the past model.  The classic Sector 9 race outline and aggressive concave work together to ensure you’ll be locked in and ready to rally from the moment you step on.  Wheel flares in the front and rear act as natural foot-stops to keep your feet from unwanted movement, while the non-invasive W-concave towards the middle of the board adds rigidity. A short wheelbase race-rocket or a surfy feeling free-rider, rip your way through any situation on the Ripped Jacko Pro.'),
('deck', 'TROPICS LEDGER DECK', 86, 'https://cdn.shopify.com/s/files/1/2291/8079/products/TROPICS-LEDGER-DECK_2048x.png?v=1522788891', 'If you think a ''ledger'' can be described as a book with lots of columns, on which an accountant keeps tracks of debits and credits, then you''re talking to the wrong people.  Our ''Ledger'' is a sleek, classic pintail made for carving and providing you with an enjoyable commute. If you''re stuck in the city, just flip it over and our updated graphic will transport you to a stress-free, palm tree-lined beach.'),
('deck', 'STACKED STRAND DECK', 69, 'https://cdn.shopify.com/s/files/1/2291/8079/products/STACKED-STRAND-DECK_2048x.png?v=1525717330', 'The 9-Ball Crew can’t stare at the bottom graphic of the new Strand too long, because we can’t stop mind-surfing the stacked lines from artist Erik Abel! Having the shortest wheelbase in this season’s bamboo collection provides the Strand with a sharp turning radius and a functional kicktail will allow you to ollie over anything that gets in your way down to the corner store.'),
('deck', 'ECLIPSE BONSAI DECK', 80, 'https://cdn.shopify.com/s/files/1/2291/8079/products/ECLIPSE-BONSAI-DECK_2048x.png?v=1525717583', 'At 42” in length, the Bonsai is the second longest board in the entire Sector 9 lineup, this season, after the 25 Year OG Pin. Drawing on our traditional heritage of pintails, this skateboard doesn’t care if you’re 6 years old or 60 – either way it’s going to show you a good time and keep you wanting to come back for more. Hopefully, it can transport you to the right-hand point artist Erik Abel has put on the bottom!'),
('deck', '25 YEAR BHNC DECK', 99, 'https://cdn.shopify.com/s/files/1/2291/8079/products/25-YEAR-BHNC-DECK_2048x.png?v=1529358769', 'The original release of the Bomb Hills Not Countries board created a memorable statement, heard around the world.  Over the years that followed, we consistently received requests to reissue this board, so it made complete sense to include it in the 25 Year Anniversary Limited Edition Series.  The deck construction on this classic shape features a unique, multi-color ply, making each board truly one of a kind! Enjoy this perfect high-speed carving vehicle that also allows you to take control of tough, steep terrain.'),
('deck', 'RAY COLLINS MERCHANT DECK', 85, 'https://cdn.shopify.com/s/files/1/2291/8079/products/RAY-COLLINS-MERCHANT-DECK_2048x.png?v=1530839476', 'Cruising and carving have never been easier, when you’re riding the Merchant, and we’ve made this ageless Sector 9 shape look better than ever with Ray’s POV from inside the barrel. The 25.75” wheelbase combined with 65MM Top Shelf wheels and Gullwing Charger trucks will provide you with the tools to draw unique lines on the pavement, and guarantee you endless fun from sunrise to sunset.'),
('deck', 'DREAM GRAVY SEMI PRO DECK', 69, 'https://cdn.shopify.com/s/files/1/2291/8079/products/DREAM-GRAVY-SEMI-PRO-DECK_2048x.png?v=1539808605', 'What’s your claim? Ben Gravy is claiming his new Semi-Pro model will provide you with the most fun you’ve ever had on a skateboard!  Purposely designed with versatility in mind, this board will allow you to body-bag your local skatepark, cruise down to your version of El Slammo for a surf check, hit every novelty skate spot in your neighborhood and will then quickly transport you to the nearest convenience store for a post-session coffee and vegan cookie. For the dream!'),
('deck', 'TACKLE FRACTAL DECK', 199, 'https://cdn.shopify.com/s/files/1/2291/8079/products/TACKLE-FRACTAL-DECK_2048x.png?v=1537907577', 'While Salty Timbers has created an angler’s dream on underside of the Tackle Fractal, we’re confident in saying this board will provide you with the type of turns that skaters dream of! The Sidewinder trucks feature a patented double kingpin style and are best suited for carving.  The knurled kingpins stay securely in place while riding and will allow you to carve harder, deeper and smoother than you’ve ever imagined!  Consistently on our best-seller list, this shape is dropped down for easy pushing, carving and pumping, and will surely provide the type of ride you’ve been craving.'),


('wheel', 'Arbor Bogart 61mm 78a White Wheels', 35, 'http://www.hawgswheels.com/pics/Boss76a.png', 'The Arbor 61mm 78a Bogart White wheels are designed for freeriding, carving, and cruising. The firm durometer maintains speed over smooth surfaces. The rounded lips and stoneground surface produce natural slides.'),
('wheel', 'Arbor Mosh 65mm 78a Blue Wheels', 37, 'http://www.hawgswheels.com/pics/Tracer78a1.png', 'The Arbor Mosh 65mm 78a Green wheels are designed for freeriding and cruising. With a firm durometer to maintain speed, the rounded lips are ideal for sliding.'),
('wheel', 'Arbor Spud 64mm 82a Red Wheels', 43, 'http://www.hawgswheels.com/pics/Zombie84a.png', 'The Arbor Spud 64mm 82a wheels are designed for freeriding. With rounded lips and stoneground surface for sliding, the firm durometer maintains a quick roll speed.'),
('wheel', 'Arbor Vice 69mm 80a White Wheels', 45, 'http://www.hawgswheels.com/pics/Monster80a.png', 'The Arbor Vice 69mm 80a White wheels are designed for freeriding. With rounded lips and stoneground surface for sliding, the firm durometer maintains a quick roll speed.'),
('wheel', 'Blood Orange Morgan 70mm 82a Lavender Wheels', 49, 'http://www.hawgswheels.com/pics/Street57mm90a.png', 'The Blood Orange Morgan 70mm 82a Lavender wheels are designed for freeriding and cruising. The tallest of the Morgan Series, the stoneground surface and rounded lips produce natural slides. The firm durometer maintains a quick roll speed over smooth terrain. '),
('wheel', 'Cadillac Sugar Mamas 65mm 78a Blue Wheels', 43, 'http://www.hawgswheels.com/pics/MiniMonster86a.png', 'The Cadillac Sugar Mamas 65mm 78a Blue wheels are designed for freeriding and cruising. With rounded lips for slides, the soft durometer absorbs shock over rough terrain. '),
('wheel', 'Hawgs Mini Monster 70mm 78a Blue Wheels', 50, 'http://www.hawgswheels.com/pics/MiniZombie78a.png', 'The Hawgs Mini Monster 70mm 78a Blue wheels are designed for cruising, carving, freeride, and downhill. With a slightly chamfered lip for grip and slip, the softer durometer absorbs shock over rough terrain. '),
('wheel', 'RAD Release 72mm 78a White Wheels', 54, 'http://www.hawgswheels.com/pics/Monster80a.png', 'The RAD Release 72mm 78a White wheels are designed for freeriding. With a stoneground surface and rounded lips for sliding, the soft durometer reduces vibration over rough terrain.  Sold in a set of 4 wheels.'),
('wheel', 'Arbor Easy Rider Outlook 69mm 78a Ghost Black Wheels', 39, 'http://www.hawgswheels.com/pics/KMFSU80a.png', 'The Arbor 69mm 78a Easy Rider Outlook wheels are designed for freeriding, carving, and cruising. The firm durometer maintains speed over smooth surfaces. The rounded lips and stoneground surface produce natural slides. '),
('wheel', 'Orangatang Onsens 58mm 100a Blue Wheels', 35, 'http://www.hawgswheels.com/pics/MiniMonster86a.png', 'The Orangatang Onsens 58mm 100a Blue wheels are designed for street, park and pool riding. With a hard durometer to maintain a fast roll speed over smooth terrain, the rounded lips provide grip in combination with the sanded finish. The core is created with heat resistant, high strength, and glass-free urethane.  Sold in a set of 4 wheels')

('truck', '180mm Paris V2 50° Matte Black Longboard Skateboard Truck', 22, 'https://www.muirskate.com/photos/products/5499/hd_product_Paris-180mm-V2-Matte-Black-%28Set-HD%29.png', 'Paris redesigned their top selling longboard trucks to bring us the new and improved Paris V2! These trucks feature a beefier hanger that is less prone to bending from all of the abuse you can dish out.The Paris V2s still have a very open, unrestrictive bushing seat that works well for those who enjoy a very carvy, surfy feeling setup. Paris also improved the design by throwing in more durable pivot cups and adding a little extra length to the kingpin.These trucks look as great as they ride! A thick powder coat not only protects the aluminum hangers and baseplates from the elements but also creates a beautiful, glossy finish. No matter what your color preference, Paris has got you covered!'),
('truck', '180mm Paris V2 50° Tiffany Longboard Skateboard Truck', 25, 'https://www.muirskate.com/photos/products/5500/hd_product_Paris-180mm-V2-Tiffany-%28Set-HD%29.png', 'Paris redesigned their top selling longboard trucks to bring us the new and improved Paris V2! These trucks feature a beefier hanger that is less prone to bending from all of the abuse you can dish out.The Paris V2s still have a very open, unrestrictive bushing seat that works well for those who enjoy a very carvy, surfy feeling setup. Paris also improved the design by throwing in more durable pivot cups and adding a little extra length to the kingpin.These trucks look as great as they ride! A thick powder coat not only protects the aluminum hangers and baseplates from the elements but also creates a beautiful, glossy finish. No matter what your color preference, Paris has got you covered!'),
('truck', '180mm Aera RF-1 Freeride 46 Degree Longboard Skateboard Truck Gray', 85, 'https://www.muirskate.com/photos/products/7819/hd_product_AERA-RF1-Longboard-Trucks-Freeride-46deg-Gray%28SET-HD%29.png', 'Are you looking for the newest truck in the market? Look no further, this is it!! This Aera Rf-1 Freeride Longboard truck is set up with 46 degree baseplates, 90a hardcore bushings and with a 180mm hanger. This truck is designed for someone looking into stepping up their game in fast freeride and downhill. A cold forged construction, machined axles and kingpins makes this truck very stable, strong, light and reliable.'),
('truck', '166mm Aera K5 Raw Precision Longboard Skateboard Trucks', 216, 'https://www.muirskate.com/photos/products/7855/hd_product_Aera-K5-Raw-176mm_42deg-Downhill-%28SET-HD%29.png', 'The Aera K5 Trucks have landed! Featuring a new sleek design, the same gangster lean, and narrower widths, the Aera K5 is one of the most trusted trucks in the game. With a hanger width of 158mm, and a number of different threaded axle options, you can be sure you''ll get the exact feel your looking for. Trucks assembled with 4140 Steel Axles and grade 8 kingpins.'),
('truck', '187mm Gullwing 10" Sidewinder II Lime Longboard Skateboard Truck', 47, 'https://www.muirskate.com/photos/products/7605/hd_product_Gullwing-Sidewinder-II-Green-%28Pair-HD%29.png', 'If you are looking for exaggerated easy turning and a smooth flow, the Gullwing Sidewinders are definitely the trucks for you. Designed to surf the street, the Gullwing Sidewinders simulate the movements that are common to surfing on an actually wave in the ocean! Surfing the desert is now possible!'),
('truck', '187mm Gullwing 10" Sidewinder II Black Longboard Skateboard Truck', 31, 'https://www.muirskate.com/photos/products/7607/hd_product_Gullwing-Sidewinder-II-Black-%28Pair-HD%29.png', 'If you are looking for exaggerated easy turning and a smooth flow, the Gullwing Sidewinders are definitely the trucks for you. Designed to surf the street, the Gullwing Sidewinders simulate the movements that are common to surfing on an actually wave in the ocean! Surfing the desert is now possible!'),
('truck', '165mm Arsenal Raw Cast Longboard Skateboard Truck', 28, 'https://www.muirskate.com/photos/products/7538/hd_product_Arsenal-180mm-50deg-Raw-Truck-%28Set-HD%29.png', 'Arsenal has designed a new high performance cast trucks with freeriding and downhill in mind. These trucks come in two different baseplate angles 44° and 50° so you can mix and match to dial in your ride. The hanger is Flipable with Custom Kingpin Hole Geometry to Maximize Bushing Contact. Arsenals cast trucks are constructed out of Heat Treated to a T6 Temper and the axles are hardened steel, making these trucks unbelievably strong'),
('truck', '178mm Bear Red Kodiak Longboard Trucks', 71, 'https://www.muirskate.com/photos/products/7525/hd_product_Bear-Kodiak-Red-Longboard-Trucks-%28SET-HD%29.png', 'The Bear Kodiak Truck features the latest in truck technology. This forged truck is one of the lightest non-precision trucks on the market. And with the eight-hole baseplate design you have even more wheelbase options to choose from! If you''re looking for a truck that that offers the precision feel without the precision dent in your wallet, then look no further, my friend!'),
('truck', '135mm Caliber The New Standard Blackout 8" Axle Skateboard Truck', 56, 'https://www.muirskate.com/photos/products/3986/hd_product_Caliber-II-Standard-148mm-Black-%28Set-HD%29.png', 'Keepin it real with the skatepark homies, Caliber has brought us the Standard Truck. Throw a set of these on your favorite pool shralper or on to your tech slide setup and get pushin'),
('truck', '183mm Gullwing White Reverse Longboard Skateboard Truck', 37, 'https://www.muirskate.com/photos/products/3419/hd_product_Gullwing-Reverse-White-%28Set-HD%29.png', 'The New Gullwing Reverse Longboard Skateboard Truck is a versatile truck capable of being used for cruising, carving, and freeriding right out of the package. The Reverse Trucks also come with RAD bushings making these trucks great for some downhill longboarding. You will have no problem mounting these trucks on your favorite Arbor or Sector 9 dropthrough deck.')
;